version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - 'rethinkdb'
    environment:
      - RETHINKDB=rethinkdb
      - PORT=8000
  rethinkdb:
    image: rethinkdb
    network_mode: "host"
    ports:
        - "8080"
        - "28015"
        - "29015"
